# Generated by Django 4.1.5 on 2023-01-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=0)),
                ('question_type', models.CharField(blank=True, choices=[('Text', 'Text'), ('Image', 'Image')], max_length=100, null=True)),
                ('suggestion_one', models.CharField(blank=True, max_length=256, null=True)),
                ('suggestion_two', models.CharField(blank=True, max_length=256, null=True)),
                ('suggestion_three', models.CharField(blank=True, max_length=256, null=True)),
                ('suggestion_four', models.CharField(blank=True, max_length=256, null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='questions-pic')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='questions-pic')),
                ('right_answer', models.IntegerField(default=0)),
                ('question_conff', models.IntegerField(default=0)),
            ],
        ),
    ]
